### ISSUE TITLE
Center align content

### ISSUE THREAD

**Issue by jim-rosales** [HalPilotte/tea-cozy#3]
I noticed that the second row of items in your container we not centered:
![screen shot 2018-03-05 at 9 42 03 pm](https://user-images.githubusercontent.com/28379087/37015892-896a0d36-20be-11e8-9f74-dd8ede49e784.png)

To fix this issue all you have to do is to add justify-content and set it so center:
```CSS
.flex-container {
  display: flex;
  width: 100%;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
}
```
![screen shot 2018-03-05 at 9 42 15 pm](https://user-images.githubusercontent.com/28379087/37015956-ce235a22-20be-11e8-89a1-85421781cd88.png)

You can read more about this property [here](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content)

Once you update your stylesheet your page should render in the following way:

https://github.com/HalPilotte/tea-cozy/blob/2edf1050827a76dff6c21903d26e6d54d2cc8a1f/style.css#L23-L28
